"""
GET /api/settings/schema — the giant functional-grouping schema the React
frontend consumes to render Settings categories.

Pure data. No DB hits, no helpers. Extracted from server.py v1.0.37k as
part of the modularisation pass (server.py was 3850 lines).
"""
from fastapi import APIRouter

router = APIRouter()


@router.get("/settings/schema")
async def get_settings_schema():
    return {
        "sections": [
            {"key": "essentials", "labelKey": "sec_essentials"},
            {"key": "gameplay", "labelKey": "sec_gameplay"},
            {"key": "world", "labelKey": "sec_world"},
            {"key": "economy", "labelKey": "sec_economy"},
            {"key": "security", "labelKey": "sec_security"},
            {"key": "users", "labelKey": "sec_users"},
            {"key": "advanced", "labelKey": "sec_advanced"},
            {"key": "automation", "labelKey": "sec_automation"},
            {"key": "discord", "labelKey": "sec_discord"},
        ],
        "categories": [
            # ------ ESSENTIALS ------
            {"key": "essentials_identity", "labelKey": "cat_essentials_identity", "icon": "Tag", "section": "essentials",
             "renderer": "dynamic", "sourceKey": "srv_general", "exportKey": "server_settings",
             "fieldKeys": ["scum.ServerName", "scum.ServerDescription", "scum.ServerBannerUrl", "scum.ServerPlaystyle",
                           "scum.WelcomeMessage", "scum.MessageOfTheDay", "scum.MessageOfTheDayCooldown"]},
            {"key": "essentials_access", "labelKey": "cat_essentials_access", "icon": "KeyRound", "section": "essentials",
             "renderer": "dynamic", "sourceKey": "srv_general", "exportKey": "server_settings",
             "fieldKeys": ["scum.ServerPassword", "scum.MaxPlayers"]},
            {"key": "essentials_performance", "labelKey": "cat_essentials_performance", "icon": "Gauge", "section": "essentials",
             "renderer": "dynamic", "sourceKey": "srv_general", "exportKey": "server_settings",
             "fieldKeys": ["scum.MinServerTickRate", "scum.MaxServerTickRate", "scum.MaxPingCheckEnabled", "scum.MaxPing",
                           "scum.MasterServerUpdateSendInterval"]},
            {"key": "essentials_launch_args", "labelKey": "cat_essentials_launch_args", "icon": "Terminal", "section": "essentials",
             "renderer": "launch_args"},
            {"key": "essentials_wipe", "labelKey": "cat_essentials_wipe", "icon": "Eraser", "section": "essentials",
             "renderer": "dynamic", "sourceKey": "srv_general", "exportKey": "server_settings",
             "fieldKeys": ["scum.PartialWipe", "scum.GoldWipe", "scum.FullWipe"]},

            # ------ GAMEPLAY ------
            {"key": "gameplay_view", "labelKey": "cat_gameplay_view", "icon": "Eye", "section": "gameplay",
             "renderer": "dynamic", "sourceKey": "srv_general", "exportKey": "server_settings",
             "fieldKeys": ["scum.AllowFirstPerson", "scum.AllowThirdPerson", "scum.AllowCrosshair", "scum.AllowMapScreen",
                           "scum.HideKillNotification", "scum.DisableExamineGhost"]},
            {"key": "gameplay_pvp_rules", "labelKey": "cat_gameplay_pvp_rules", "icon": "Swords", "section": "gameplay",
             "renderer": "dynamic", "sourceKey": "srv_general", "exportKey": "server_settings",
             "fieldKeys": ["scum.AllowKillClaiming", "scum.AllowComa", "scum.AllowMinesAndTraps", "scum.AllowSkillGainInSafeZones",
                           "scum.AllowEvents", "scum.LogoutTimer", "scum.LogoutTimerWhileCaptured", "scum.LogoutTimerInBunker"]},
            {"key": "gameplay_chat", "labelKey": "cat_gameplay_chat", "icon": "MessageCircle", "section": "gameplay",
             "renderer": "dynamic", "sourceKey": "srv_general", "exportKey": "server_settings",
             "fieldKeys": ["scum.LimitGlobalChat", "scum.AllowGlobalChat", "scum.AllowLocalChat", "scum.AllowSquadChat", "scum.AllowAdminChat"]},
            {"key": "gameplay_voting", "labelKey": "cat_gameplay_voting", "icon": "Vote", "section": "gameplay",
             "renderer": "dynamic", "sourceKey": "srv_general", "exportKey": "server_settings",
             "fieldKeys": ["scum.AllowVoting", "scum.VotingDuration", "scum.PlayerMinimalVotingInterest", "scum.PlayerPositiveVotePercentage"]},
            {"key": "gameplay_respawn", "labelKey": "cat_gameplay_respawn", "icon": "RotateCcw", "section": "gameplay",
             "renderer": "dynamic", "sourceKey": "srv_respawn", "exportKey": "server_settings"},
            {"key": "gameplay_damage", "labelKey": "cat_gameplay_damage", "icon": "Swords", "section": "gameplay",
             "renderer": "dynamic", "sourceKey": "srv_damage", "exportKey": "server_settings"},
            {"key": "gameplay_progression", "labelKey": "cat_gameplay_progression", "icon": "TrendingUp", "section": "gameplay",
             "renderer": "dynamic", "sourceKey": "srv_general", "exportKey": "server_settings",
             "fieldKeys": ["scum.FameGainMultiplier", "scum.FamePointPenaltyOnDeath", "scum.FamePointPenaltyOnKilled",
                           "scum.FamePointRewardOnKill", "scum.LogSuicides", "scum.EnableSpawnOnGround"]},
            {"key": "gameplay_skills", "labelKey": "cat_gameplay_skills", "icon": "GraduationCap", "section": "gameplay",
             "renderer": "dynamic", "sourceKey": "srv_features", "exportKey": "server_settings",
             "fieldKeys": ["scum.ArcherySkillMultiplier", "scum.AviationSkillMultiplier", "scum.AwarenessSkillMultiplier",
                           "scum.BrawlingSkillMultiplier", "scum.CamouflageSkillMultiplier", "scum.CookingSkillMultiplier",
                           "scum.DemolitionSkillMultiplier", "scum.DrivingSkillMultiplier", "scum.EnduranceSkillMultiplier",
                           "scum.EngineeringSkillMultiplier", "scum.FarmingSkillMultiplier", "scum.HandgunSkillMultiplier",
                           "scum.MedicalSkillMultiplier", "scum.MeleeWeaponsSkillMultiplier", "scum.MotorcycleSkillMultiplier",
                           "scum.RiflesSkillMultiplier", "scum.RunningSkillMultiplier", "scum.SnipingSkillMultiplier",
                           "scum.StealthSkillMultiplier", "scum.SurvivalSkillMultiplier", "scum.ThieverySkillMultiplier"]},
            {"key": "gameplay_stamina", "labelKey": "cat_gameplay_stamina", "icon": "Activity", "section": "gameplay",
             "renderer": "dynamic", "sourceKey": "srv_features", "exportKey": "server_settings",
             "fieldKeys": ["scum.MovementInertiaAmount", "scum.StaminaDrainOnJumpMultiplier", "scum.StaminaDrainOnClimbMultiplier",
                           "scum.DisableExhaustion", "scum.BodySimulationSpeedMultiplier"]},
            {"key": "gameplay_new_players", "labelKey": "cat_gameplay_new_players", "icon": "UserPlus", "section": "gameplay",
             "renderer": "dynamic", "sourceKey": "srv_features", "exportKey": "server_settings",
             "fieldKeys": ["scum.EnableNewPlayerProtection", "scum.NewPlayerProtectionDuration", "scum.NameChangeCooldown", "scum.NameChangeCost"]},

            # ------ WORLD ------
            {"key": "world_time", "labelKey": "cat_world_time", "icon": "Clock", "section": "world",
             "renderer": "dynamic", "sourceKey": "srv_world", "exportKey": "server_settings",
             "fieldKeys": ["scum.StartTimeOfDay", "scum.TimeOfDaySpeed", "scum.NighttimeDarkness", "scum.SunriseTime", "scum.SunsetTime", "scum.EnableFog"]},
            {"key": "world_spawn_limits", "labelKey": "cat_world_spawn_limits", "icon": "Users", "section": "world",
             "renderer": "dynamic", "sourceKey": "srv_world", "exportKey": "server_settings",
             "fieldKeys": ["scum.MaxAllowedBirds", "scum.MaxAllowedCharacters", "scum.MaxAllowedPuppets",
                           "scum.MaxAllowedAnimals", "scum.MaxAllowedNPCs", "scum.MaxAllowedDrones"]},
            {"key": "world_puppets", "labelKey": "cat_world_puppets", "icon": "Skull", "section": "world",
             "renderer": "dynamic", "sourceKey": "srv_world", "exportKey": "server_settings",
             "fieldKeys": ["scum.PuppetsCanOpenDoors", "scum.PuppetsCanVaultWindows", "scum.PuppetHealthMultiplier",
                           "scum.PuppetRunningSpeedMultiplier", "scum.PuppetLimpingEnabled", "scum.DisableSuicidePuppetSpawning"]},
            {"key": "world_armed_npcs", "labelKey": "cat_world_armed_npcs", "icon": "Crosshair", "section": "world",
             "renderer": "dynamic", "sourceKey": "srv_world", "exportKey": "server_settings",
             "fieldKeys": ["scum.ArmedNPCDifficultyLevel", "scum.ArmedNPCHealthMultiplier", "scum.ArmedNPCDamageMultiplier",
                           "scum.ArmedNPCSpreadMultiplier", "scum.ArmedNPCRunningSpeedMultiplier", "scum.ArmedNPCLimpingEnabled",
                           "scum.ProbabilityForArmedNPCToDropItemFromHandsWhenSearched"]},
            {"key": "world_sentries", "labelKey": "cat_world_sentries", "icon": "Radar", "section": "world",
             "renderer": "dynamic", "sourceKey": "srv_world", "exportKey": "server_settings",
             "fieldKeys": ["scum.DisableSentrySpawning", "scum.EnableSentryRespawning", "scum.SentryHealthMultiplier",
                           "scum.BaseBuildingAttackerSentryHealthMultiplier", "scum.DropshipHealthMultiplier"]},
            {"key": "world_animals", "labelKey": "cat_world_animals", "icon": "Rabbit", "section": "world",
             "renderer": "dynamic", "sourceKey": "srv_world", "exportKey": "server_settings",
             "fieldKeys": ["scum.BearMaxHealthMultiplier", "scum.BoarMaxHealthMultiplier", "scum.ChickenMaxHealthMultiplier",
                           "scum.DeerMaxHealthMultiplier", "scum.DonkeyMaxHealthMultiplier", "scum.GoatMaxHealthMultiplier",
                           "scum.HorseMaxHealthMultiplier", "scum.RabbitMaxHealthMultiplier", "scum.WolfMaxHealthMultiplier"]},
            {"key": "world_hunts", "labelKey": "cat_world_hunts", "icon": "Target", "section": "world",
             "renderer": "dynamic", "sourceKey": "srv_world", "exportKey": "server_settings",
             "fieldKeys": ["scum.MaxAllowedHunts", "scum.HuntFailureTime", "scum.HuntFailureDistance",
                           "scum.HuntTriggerChanceOverride_ContinentalForest", "scum.HuntTriggerChanceOverride_ContinentalMeadow",
                           "scum.HuntTriggerChanceOverride_Mediterranean", "scum.HuntTriggerChanceOverride_Mountain",
                           "scum.HuntTriggerChanceOverride_Urban", "scum.HuntTriggerChanceOverride_Village"]},
            {"key": "world_bunkers", "labelKey": "cat_world_bunkers", "icon": "DoorClosed", "section": "world",
             "renderer": "dynamic", "sourceKey": "srv_world", "exportKey": "server_settings",
             "fieldKeys": ["scum.AbandonedBunkerMaxSimultaneouslyActive", "scum.AbandonedBunkerActiveDurationHours",
                           "scum.AbandonedBunkerKeyCardActiveDurationHours", "scum.SecretBunkerKeyCardActiveDurationHours",
                           "scum.MaxAllowedKillboxKeycards", "scum.MaxAllowedKillboxKeycards_PoliceStation",
                           "scum.MaxAllowedKillboxKeycards_RadiationZone", "scum.AbandonedBunkerBCUTerminalCooldown"]},
            {"key": "world_cargo", "labelKey": "cat_world_cargo", "icon": "Package", "section": "world",
             "renderer": "dynamic", "sourceKey": "srv_world", "exportKey": "server_settings",
             "fieldKeys": ["scum.CargoDropCooldownMinimum", "scum.CargoDropCooldownMaximum", "scum.CargoDropFallDelay",
                           "scum.CargoDropFallDuration", "scum.CargoDropSelfdestructTime"]},
            {"key": "world_encounters", "labelKey": "cat_world_encounters", "icon": "Zap", "section": "world",
             "renderer": "dynamic", "sourceKey": "srv_world", "exportKey": "server_settings",
             "fieldKeys": ["scum.EncounterBaseCharacterAmountMultiplier", "scum.EncounterExtraCharacterPerPlayerMultiplier",
                           "scum.EncounterExtraCharacterPlayerCapMultiplier", "scum.EncounterCharacterRespawnTimeMultiplier",
                           "scum.EncounterHordeActivationChanceMultiplier", "scum.EncounterHordeSpawnDistanceMultiplier",
                           "scum.EncounterNeverRespawnCharacters", "scum.PuppetWorldEncounterSpawnWeightMultiplier"]},
            {"key": "world_map", "labelKey": "cat_world_map", "icon": "Map", "section": "world",
             "renderer": "dynamic", "sourceKey": "srv_world", "exportKey": "server_settings",
             "fieldKeys": ["scum.CustomMapEnabled", "scum.CustomMapCenterXCoordinate", "scum.CustomMapCenterYCoordinate",
                           "scum.CustomMapWidth", "scum.CustomMapHeight", "scum.ShouldDestroyEntitiesOutsideMapLimitsOnRestart"]},

            # ------ ECONOMY ------
            {"key": "economy_main", "labelKey": "cat_economy_main", "icon": "Banknote", "section": "economy",
             "renderer": "dynamic", "sourceKey": "economy_override", "exportKey": "economy"},
            {"key": "economy_traders", "labelKey": "cat_economy_traders", "icon": "Store", "section": "economy",
             "renderer": "traders", "sourceKey": "economy_traders", "exportKey": "economy"},
            {"key": "economy_resources", "labelKey": "cat_economy_resources", "icon": "Droplet", "section": "economy",
             "renderer": "dynamic", "sourceKey": "srv_features", "exportKey": "server_settings",
             "fieldKeys": ["scum.WaterPricePerUnitMultiplier", "scum.WaterPeriodicInitialAmountMultiplier", "scum.WaterPeriodicMaxAmountMultiplier",
                           "scum.WaterPeriodicReplenishAmountMultiplier", "scum.WaterPeriodicReplenishIntervalMultiplier",
                           "scum.GasolinePricePerUnitMultiplier", "scum.GasolinePeriodicInitialAmountMultiplier", "scum.GasolinePeriodicMaxAmountMultiplier",
                           "scum.PropanePricePerUnitMultiplier", "scum.PropanePeriodicInitialAmountMultiplier"]},
            # v1.0.36 fix: stock-cap tab only — physics fields excluded so they
            # don't double up with Advanced → Vehicle Physics.
            {"key": "economy_vehicles_stock", "labelKey": "cat_economy_vehicles_stock", "icon": "Truck", "section": "economy",
             "renderer": "dynamic", "sourceKey": "srv_vehicles", "exportKey": "server_settings",
             "excludeFieldKeys": ["scum.FuelDrainFromEngineMultiplier", "scum.BatteryDrainFromEngineMultiplier",
                                  "scum.BatteryDrainFromDevicesMultiplier", "scum.BatteryDrainFromInactivityMultiplier",
                                  "scum.BatteryChargeWithAlternatorMultiplier", "scum.BatteryChargeWithDynamoMultiplier",
                                  "scum.MaximumTimeOfVehicleInactivity", "scum.MaximumTimeForVehiclesInForbiddenZones",
                                  "scum.LogVehicleDestroyed"]},
            {"key": "economy_loot", "labelKey": "cat_economy_loot", "icon": "Package", "section": "economy",
             "renderer": "dynamic", "sourceKey": "srv_features", "exportKey": "server_settings",
             "fieldKeys": ["scum.SpawnerProbabilityMultiplier", "scum.ExamineSpawnerProbabilityMultiplier",
                           "scum.ExamineSpawnerExpirationTimeMultiplier", "scum.SpawnerExpirationTimeMultiplier",
                           "scum.EnableItemCooldownGroups", "scum.ItemCooldownGroupsDurationMultiplier"]},
            {"key": "economy_quests", "labelKey": "cat_economy_quests", "icon": "ScrollText", "section": "economy",
             "renderer": "dynamic", "sourceKey": "srv_features", "exportKey": "server_settings",
             "fieldKeys": ["scum.QuestsEnabled", "scum.QuestsGlobalCycleDuration", "scum.MaxQuestsPerCyclePerTrader",
                           "scum.MaxSimultaneousQuestsPerTrader", "scum.QuestsTraderRefillCooldown",
                           "scum.QuestsPhoneRefillCooldown", "scum.QuestsNoticeBoardRefillCooldown", "scum.QuestRequirementsBlockTradeableItems"]},

            # ------ SECURITY (Raid & Base) ------
            {"key": "security_base_building", "labelKey": "cat_security_base_building", "icon": "Hammer", "section": "security",
             "renderer": "dynamic", "sourceKey": "srv_features", "exportKey": "server_settings",
             "fieldKeys": ["scum.FlagOvertakeDuration", "scum.MaximumAmountOfElementsPerFlag",
                           "scum.ExtraElementsPerFlagForAdditionalSquadMember", "scum.MaximumNumberOfExpandedElementsPerFlag",
                           "scum.AllowMultipleFlagsPerPlayer", "scum.AllowFlagPlacementOnBBElements",
                           "scum.AllowFloorPlacementOnHalfAndLowWalls", "scum.AllowWallPlacementOnHalfAndLowWalls",
                           "scum.ChestAcquisitionDuration"]},
            {"key": "security_raid_protection", "labelKey": "cat_security_raid_protection", "icon": "ShieldAlert", "section": "security",
             "renderer": "dynamic", "sourceKey": "srv_features", "exportKey": "server_settings",
             "fieldKeys": ["scum.RaidProtectionType", "scum.RaidProtectionEnableLog",
                           "scum.RaidProtectionFlagSpecificChangeSettingCooldown", "scum.RaidProtectionFlagSpecificChangeSettingPrice",
                           "scum.RaidProtectionFlagSpecificMaxProtectionTime", "scum.RaidProtectionOfflineProtectionStartDelay",
                           "scum.RaidProtectionOfflineMaxProtectionTime", "scum.RaidProtectionGlobalShouldShowRaidTimesMessage",
                           "scum.RaidProtectionGlobalShouldShowRaidAnnouncementMessage", "scum.RaidProtectionGlobalShouldShowRaidStartEndMessages"]},
            {"key": "security_raid_times", "labelKey": "cat_security_raid_times", "icon": "CalendarClock", "section": "security",
             "renderer": "raid_times", "sourceKey": "raid_times", "exportKey": "raid_times"},
            {"key": "security_turrets", "labelKey": "cat_security_turrets", "icon": "Crosshair", "section": "security",
             "renderer": "dynamic", "sourceKey": "srv_features", "exportKey": "server_settings",
             "fieldKeys": ["scum.TurretsAttackPrisoners", "scum.TurretsAttackPuppets", "scum.TurretsAttackVehicles",
                           "scum.TurretsAttackSentries", "scum.TurretsAttackAnimals", "scum.TurretsAttackArmedNPCs"]},
            {"key": "security_anticheat", "labelKey": "cat_security_anticheat", "icon": "ShieldCheck", "section": "security",
             "renderer": "dynamic", "sourceKey": "srv_general", "exportKey": "server_settings",
             "fieldKeys": ["scum.RustyLocksLogging", "scum.PlaySafeIdProtection", "scum.DeleteInactiveUsers",
                           "scum.DaysSinceLastLoginToBecomeInactive", "scum.DeleteBannedUsers", "scum.LogChestOwnership"]},

            # ------ USERS ------
            {"key": "users_admins", "labelKey": "cat_users_admins", "icon": "ShieldUser", "renderer": "user_list",
             "exportKey": "admins", "commonFlags": ["godmode", "moderator", "ghost", "commentator"], "section": "users"},
            {"key": "users_server_admins", "labelKey": "cat_users_server_admins", "icon": "UserCog", "renderer": "user_list",
             "exportKey": "server_admins", "commonFlags": ["serveradmin"], "section": "users"},
            {"key": "users_whitelisted", "labelKey": "cat_users_whitelisted", "icon": "ListChecks", "renderer": "user_list",
             "exportKey": "whitelisted", "commonFlags": ["vip"], "section": "users"},
            {"key": "users_exclusive", "labelKey": "cat_users_exclusive", "icon": "UserCheck", "renderer": "user_list",
             "exportKey": "exclusive", "commonFlags": ["vip"], "section": "users"},
            {"key": "users_banned", "labelKey": "cat_users_banned", "icon": "UserX", "renderer": "user_list",
             "exportKey": "banned", "commonFlags": ["permanent"], "section": "users"},
            {"key": "users_silenced", "labelKey": "cat_users_silenced", "icon": "MicOff", "renderer": "user_list",
             "exportKey": "silenced", "commonFlags": ["voice", "chat"], "section": "users"},

            # ------ ADVANCED ------
            {"key": "advanced_vehicles_physics", "labelKey": "cat_advanced_vehicles_physics", "icon": "Fuel", "section": "advanced",
             "renderer": "dynamic", "sourceKey": "srv_vehicles", "exportKey": "server_settings",
             "fieldKeys": ["scum.FuelDrainFromEngineMultiplier", "scum.BatteryDrainFromEngineMultiplier",
                           "scum.BatteryDrainFromDevicesMultiplier", "scum.BatteryDrainFromInactivityMultiplier",
                           "scum.BatteryChargeWithAlternatorMultiplier", "scum.BatteryChargeWithDynamoMultiplier",
                           "scum.MaximumTimeOfVehicleInactivity", "scum.MaximumTimeForVehiclesInForbiddenZones",
                           "scum.LogVehicleDestroyed"]},
            {"key": "advanced_squads", "labelKey": "cat_advanced_squads", "icon": "Users", "section": "advanced",
             "renderer": "dynamic", "sourceKey": "srv_features", "exportKey": "server_settings",
             "fieldKeys": ["scum.SquadMemberCountAtIntLevel1", "scum.SquadMemberCountAtIntLevel2",
                           "scum.SquadMemberCountAtIntLevel3", "scum.SquadMemberCountAtIntLevel4",
                           "scum.SquadMemberCountAtIntLevel5", "scum.SquadMemberCountLimitForPunishment",
                           "scum.RTSquadProbationDuration", "scum.SquadMoneyPenaltyPerPrevSquadMember",
                           "scum.SquadFamePointsPenaltyPerPrevSquadMember", "scum.EnableSquadMemberNameWidget"]},
            {"key": "advanced_custom_ini", "labelKey": "cat_advanced_custom_ini", "icon": "FileCode", "section": "advanced",
             "renderer": "dynamic", "sourceKey": "custom_ini", "exportKey": None},
            {"key": "advanced_beta_settings", "labelKey": "cat_advanced_beta_settings", "icon": "FlaskConical",
             "section": "advanced", "renderer": "beta_settings", "sourceKey": "beta_settings", "exportKey": None},

            # ------ AUTOMATION ------
            {"key": "automation_restart", "labelKey": "cat_automation_restart", "icon": "RefreshCw", "section": "automation",
             "renderer": "automation_restart"},
            {"key": "automation_update", "labelKey": "cat_automation_update", "icon": "Download", "section": "automation",
             "renderer": "automation_update"},

            # ------ DISCORD ------
            {"key": "discord_webhooks", "labelKey": "cat_discord_webhooks", "icon": "Webhook", "section": "discord",
             "renderer": "discord"},

            # ------ CLIENT GAME (moved under Gameplay) ------
            {"key": "gameplay_client_game", "labelKey": "cat_client_game", "icon": "Gamepad2", "section": "gameplay",
             "renderer": "dynamic", "sourceKey": "client_game", "exportKey": "gameusersettings"},
        ],
    }
